### ISSUE TITLE
Can't get pdf_converter.py to work

### ISSUE THREAD

**Issue by Barabazs** [bsdz/remarkable-layers#1]
Running pdf_converter.py gives me the following output.

```
INFO:__main__:Processing PDF file 'test.pdf'
INFO:__main__:Extracting to SVG page 1
INFO:__main__:
** (inkscape:348140): WARNING **: 18:22:53.767: Invalid option --pdf-poppler

Traceback (most recent call last):
  File "pdf_converter.py", line 394, in <module>
    extract_svg_page(
  File "pdf_converter.py", line 252, in extract_svg_page
    resize_doc(stage_svg)
  File "pdf_converter.py", line 49, in resize_doc
    root = ET.fromstring(stage_svg.read_bytes())
  File "/usr/lib/python3.8/pathlib.py", line 1220, in read_bytes
    with self.open(mode='rb') as f:
  File "/usr/lib/python3.8/pathlib.py", line 1213, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1069, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'test/page_1.svg'

```

Any idea what I'm doing wrong?

**Comment by bsdz** [comment]
Which version of Inkscape are you using? I used this one:

```bash
$ inkscape --version
Inkscape 1.0 (1.0+r73+1)
    Pango version: 1.44.7
```

**Comment by Barabazs** [comment]
Thank you for responding so quickly.

I was using the default version on Ubuntu (Inkscape 0.92.5 (2060ec1f9f, 2020-04-08)).
With the latest snap it runs correctly.

Thank you.
