### ISSUE TITLE
installing requisites fail

### ISSUE THREAD

**Issue by micheledicosmo** [bsdz/remarkable-layers#10]
I get this from windows, ubuntu with pip3 -r and ubuntu with the standard installation method in the readme:

```
  Building wheel for potrace (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmp78hjnr81 build_wheel /tmp/tmpz8jw052h
       cwd: /tmp/pip-install-g2ufcvlu/potrace
  Complete output (36 lines):
  Traceback (most recent call last):
    File "/tmp/pip-install-g2ufcvlu/potrace/setup.py", line 29, in <module>
      build(setup_kwargs)
    File "/tmp/pip-install-g2ufcvlu/potrace/build.py", line 23, in build
      extra_compile_args = pkg_config("libagg", '--cflags')
    File "/tmp/pip-install-g2ufcvlu/potrace/build.py", line 13, in pkg_config
      return subprocess.check_output(["pkg-config", command, pkg_name]).decode(
    File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/usr/lib/python3.8/subprocess.py", line 489, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'pkg-config'
  Traceback (most recent call last):
    File "/tmp/tmp78hjnr81", line 280, in <module>
      main()
    File "/tmp/tmp78hjnr81", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmp78hjnr81", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-dpy19p9x/overlay/lib/python3.8/site-packages/poetry/core/masonry/api.py", line 57, in build_wheel
      return unicode(WheelBuilder.make_in(poetry, Path(wheel_directory)))
    File "/tmp/pip-build-env-dpy19p9x/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 59, in make_in
      wb.build()
    File "/tmp/pip-build-env-dpy19p9x/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 89, in build
      self._build(zip_file)
    File "/tmp/pip-build-env-dpy19p9x/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 121, in _build
      self._run_build_command(setup)
    File "/tmp/pip-build-env-dpy19p9x/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 149, in _run_build_command
      subprocess.check_call(
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/usr/bin/python3', '/tmp/pip-install-g2ufcvlu/potrace/setup.py', 'build', '-b', '/tmp/pip-install-g2ufcvlu/potrace/build']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for potrace
```

**Comment by bsdz** [comment]
You need to install the pypotrace build dependencies first:

```bash
$ sudo apt-get install build-essential python-dev libagg-dev libpotrace-dev pkg-config
```

See https://pypi.org/project/pypotrace/ for details. Hopefully should build and install after that.

**Comment by micheledicosmo** [comment]
thanks. that worked!
